<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>JalaliTray</AssemblyName>
    <RootNamespace>JalaliTray</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon></ApplicationIcon>
    <Version>1.0.0</Version>
    <NoWarn>$(NoWarn);WPF0001;WFO0003</NoWarn>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Fonts/*.ttf" />
    <None Include="Fonts/OFL.txt" />
  </ItemGroup>

</Project>
